In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('df.csv')

In [5]:
total_count = df.shape[0]
df

    length  width  height  net_weight  gross_weight  volume
0     41.0   41.0    18.0         9.7          10.3   0.030
1     24.0   23.0    20.0         0.4           0.7   0.011
2     80.0   55.0    45.0        16.0          29.0   0.198
3     34.0   23.0    27.0         1.0           1.5   0.021
4     57.0   47.0    47.0        11.0          21.0   0.126
5     80.0   65.0    45.0        25.0          35.0   0.234
6     80.0   55.0    45.0        68.0          81.0   0.198
7     17.0   14.0    13.0         0.3           0.4   0.003
8     24.0   23.0    20.0         3.3           3.6   0.011
9     24.0   23.0    20.0         0.3           0.6   0.011
10    41.0   41.0    18.0         1.2           1.8   0.030
11    17.0   14.0    13.0         0.8           0.9   0.003
12    17.0   14.0    13.0         0.1           0.2   0.003
13    24.0   23.0    20.0         0.2           0.5   0.011
14    17.0   14.0    13.0         0.1           0.2   0.003
15    17.0   14.0    13.0         0.7           0.8   0.003
16    17.0   14.0    13.0         0.7           0.8   0.003
17    24.0   23.0    20.0         0.2           0.5   0.011

In [6]:
total_net = df['net_weight'].sum()
total_gross = df['gross_weight'].sum()
total_volume = df['volume'].sum()

In [7]:
total_index = f'Total: {total_count}'

In [23]:
df.loc[total_index] = {'net_weight': total_net, 'gross_weight': total_gross, 'volume': total_volume}

In [24]:
clean_total = df.fillna('')

In [26]:
clean_total

          length width height  net_weight  gross_weight  volume
0           41.0  41.0   18.0         9.7          10.3   0.030
1           24.0  23.0   20.0         0.4           0.7   0.011
2           80.0  55.0   45.0        16.0          29.0   0.198
3           34.0  23.0   27.0         1.0           1.5   0.021
4           57.0  47.0   47.0        11.0          21.0   0.126
5           80.0  65.0   45.0        25.0          35.0   0.234
6           80.0  55.0   45.0        68.0          81.0   0.198
7           17.0  14.0   13.0         0.3           0.4   0.003
8           24.0  23.0   20.0         3.3           3.6   0.011
9           24.0  23.0   20.0         0.3           0.6   0.011
10          41.0  41.0   18.0         1.2           1.8   0.030
11          17.0  14.0   13.0         0.8           0.9   0.003
12          17.0  14.0   13.0         0.1           0.2   0.003
13          24.0  23.0   20.0         0.2           0.5   0.011
14          17.0  14.0   13.0         0.1           0.2   0.003
15          17.0  14.0   13.0         0.7           0.8   0.003
16          17.0  14.0   13.0         0.7           0.8   0.003
17          24.0  23.0   20.0         0.2           0.5   0.011
Total: 18                           139.0         188.8   0.910